# Generated by Django 4.0 on 2022-05-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialnotification',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
