# Generated by Django 4.0 on 2022-05-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0002_officialnotification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialnotification',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
