# Generated by Django 4.0 on 2022-05-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0005_buildingunit_supplyregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('inventory', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='supplyregistration',
            name='building_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_unit', to='plaza.buildingunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyregistration',
            name='country_yard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_yard', to='plaza.countryyard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildingunit',
            name='unit_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplyregistration',
            name='items',
            field=models.ManyToManyField(to='plaza.SupplyItem'),
        ),
    ]
