# Generated by Django 4.0 on 2022-05-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0006_supplyitem_supplyregistration_building_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specialrequest',
            name='responder',
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='building_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sr_building_unit', to='plaza.buildingunit'),
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='country_yard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sr_country_yard', to='plaza.countryyard'),
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='room_num',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
