# Generated by Django 4.0 on 2022-05-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0007_remove_specialrequest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialrequest',
            name='resolved_by_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='resolved_by_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplyregistration',
            name='resolved_by_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplyregistration',
            name='resolved_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
