# Generated by Django 4.0 on 2022-05-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0008_specialrequest_resolved_by_applicant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='building_subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sr_building_subunit', to='plaza.buildingsubunit'),
        ),
        migrations.AddField(
            model_name='supplyregistration',
            name='building_subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_subunit', to='plaza.buildingsubunit'),
        ),
    ]
