# Generated by Django 4.0 on 2022-05-30 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0009_buildingsubunit_specialrequest_building_subunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs_confirm', to='plaza.buildingsubunit')),
                ('building_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bu_confirm', to='plaza.buildingunit')),
                ('country_yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cy_confirm', to='plaza.countryyard')),
                ('special_requests', models.ManyToManyField(to='plaza.SpecialRequest')),
                ('supply_requests', models.ManyToManyField(to='plaza.SupplyRegistration')),
            ],
        ),
    ]
