# Generated by Django 4.0 on 2022-05-30 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0010_itemconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyregistration',
            name='building_subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bs', to='plaza.buildingsubunit'),
        ),
        migrations.AlterField(
            model_name='supplyregistration',
            name='building_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bu', to='plaza.buildingunit'),
        ),
        migrations.AlterField(
            model_name='supplyregistration',
            name='country_yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cy', to='plaza.countryyard'),
        ),
    ]
