# Generated by Django 4.0 on 2022-05-30 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0011_alter_supplyregistration_building_subunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialrequest',
            name='building_subunit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bs_special', to='plaza.buildingsubunit'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='building_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bu_special', to='plaza.buildingunit'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='country_yard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cy_special', to='plaza.countryyard'),
        ),
    ]
