# Generated by Django 4.0 on 2022-05-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0014_alter_supplyregistration_building_subunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialrequest',
            name='room_num',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
