# Generated by Django 4.0 on 2022-05-30 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0016_alter_specialrequest_building_subunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialrequest',
            name='country_yard',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='cy_special', to='plaza.countryyard'),
            preserve_default=False,
        ),
    ]
