# Generated by Django 4.0 on 2022-05-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0018_alter_countryyard_yard_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconfirmation',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='specialrequest',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplyregistration',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
