# Generated by Django 4.0 on 2022-06-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0019_itemconfirmation_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialrequest',
            name='resolved_by_applicant',
        ),
        migrations.RemoveField(
            model_name='specialrequest',
            name='resolved_by_staff',
        ),
    ]
