# Generated by Django 4.0 on 2022-06-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0020_remove_specialrequest_resolved_by_applicant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkingWaterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=16)),
                ('resolved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('building_subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs_water', to='plaza.buildingsubunit')),
                ('building_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bu_water', to='plaza.buildingunit')),
                ('country_yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cy_water', to='plaza.countryyard')),
            ],
        ),
    ]
