# Generated by Django 4.0 on 2022-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0021_drinkingwaterregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkingwaterregistration',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
