# Generated by Django 4.0 on 2022-06-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plaza', '0022_alter_drinkingwaterregistration_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingsubunit',
            options={'ordering': ['unit_num']},
        ),
        migrations.AlterModelOptions(
            name='buildingunit',
            options={'ordering': ['unit_num']},
        ),
        migrations.AlterModelOptions(
            name='countryyard',
            options={'ordering': ['yard_num']},
        ),
        migrations.AlterModelOptions(
            name='drinkingwaterregistration',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='itemconfirmation',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='specialrequest',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='supplyregistration',
            options={'ordering': ['-created_on']},
        ),
    ]
