# Generated by Django 4.0 on 2022-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidbasicinfo',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
